version: "3"
services:
    php7:
      build:
        context: .
        dockerfile: ./etc/docker/dockerfile_php_7
      volumes:
        - ./:/var/www/html:cached
        - ./etc/php:/usr/local/etc/php
        - ./etc/apache2/apache2.conf:/etc/apache2/conf-enabled/apache2.conf
        - ./etc/apache2/hosts.conf:/etc/apache2/sites-enabled/hosts.conf
      ports:
        - "80:80"
        - "8080:8080"
      links:
        - mysql

    mysql:
      image: mysql:8.0.13
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=testtech
        - MYSQL_DATABASE=testtech
      volumes:
        - ./etc/mysql:/docker-entrypoint-initdb.d
      command: --default-authentication-plugin=mysql_native_password