FROM php:7.2.12-apache

RUN apt-get update && \
    apt-get install -y \
        zlib1g-dev

RUN apt-get install -y \
        libxml2-dev

RUN /usr/local/bin/docker-php-ext-install mysqli pdo pdo_mysql zip xmlwriter mbstring
RUN apt-get install libssl-dev -y

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

RUN /usr/local/bin/docker-php-ext-install zip

RUN a2enmod rewrite
RUN usermod -u 1000 www-data
RUN usermod -G staff www-data